# Generated by Django 4.0.4 on 2022-05-11 16:39

from django.db import migrations, models
import flightplan.models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(default='2022-05-16', verbose_name='Start Date')),
                ('enddate', models.DateField(default='2022-07-15', verbose_name='End Date')),
                ('pic', models.CharField(default='', max_length=150, verbose_name='Pilot in Command (PIC)')),
                ('vo', models.CharField(blank=True, max_length=150, verbose_name='Visual Observers')),
                ('tp', models.TextField(blank=True, help_text='Enter other PICs here.', verbose_name='Test Personnel')),
                ('drone_id', models.CharField(default='', max_length=15, verbose_name='Drone FAA Number')),
                ('project_number', models.CharField(default='', max_length=150, verbose_name="Internal Project Number (please don't use real ones for now)")),
                ('airspace', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('class_a', 'Class A'), ('class_b', 'Class B'), ('class_c', 'Class C'), ('class_d', 'Class D'), ('class_e', 'Class E'), ('class_g', 'Class G'), ('restricted', 'Restricted')], max_length=100, verbose_name='Classes of Airspace.')),
                ('part107compliant', models.BooleanField(default=True, verbose_name='Complies with all of Part 107 and does not require Waiver or Airspace Authorization')),
                ('restrictedairspace', models.BooleanField(default=False, verbose_name='Operations conducted in airspace controlled by entity other than the FAA (e.g. Restricted Area)')),
                ('restrictedairspaceexplain', models.TextField(blank=True, help_text='If unable, write "Unable due to sponsor constraints"', verbose_name='Explain / confirm airspace permissions. Include name, title, and phone number of person granting permissions')),
                ('waiver', models.BooleanField(blank=True, default=False, verbose_name='Requires FAA Waiver or Airspace Authorization.')),
                ('waiverreason', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('section_25', '107.25 - Operations from a moving vehicle or aircraft'), ('section_29', '107.29 - Daylight operation'), ('section_31', '107.31 - Visual line of sight aircraft operation'), ('section_33', '107.33 - Visual observer'), ('section_35', '107.35 - Operation of multiple sUAS'), ('section_37a', '107.37(a) - Yielding the right of way'), ('section_39', '107.39 - Operations over people'), ('section_41', '107.41 - Operation in certain airspace'), ('section_51a', '107.51(a) - Operating limitations: ground speed'), ('section_51c', '107.51(c) - Operating limitations: altitude'), ('section_51d', '107.51(d) - Operating limitations: minimum distance from clouds')], max_length=100, verbose_name='Part 107 Section Waiver Reason.')),
                ('waivernumber', models.CharField(blank=True, max_length=100, verbose_name='FAA Waiver Authorization Number')),
                ('waiverexpiration', models.DateField(default='2022-05-11', verbose_name='FAA Waiver Expiration Date')),
                ('max_speed', models.FloatField(default=0, verbose_name='Max Speed (in m/s)')),
                ('max_altitude', models.FloatField(default=0, verbose_name='Max Altitude AGL (in m)')),
                ('duration', models.CharField(default='', max_length=100, verbose_name='Estimated flight duration / total flight time (in hrs)')),
                ('testcardfile', models.FileField(blank=True, upload_to='', validators=[flightplan.models.validate_ppt_file_extension], verbose_name='Flight Test Card (.ppt)')),
                ('hazardpatternfile', models.FileField(blank=True, upload_to='', validators=[flightplan.models.validate_ppt_file_extension], verbose_name='Hazard Pattern Card (.ppt)')),
                ('kmlfile', models.FileField(blank=True, upload_to='', validators=[flightplan.models.validate_kml_file_extension], verbose_name='KML File (.kml)')),
                ('imagefile', models.ImageField(blank=True, upload_to='', verbose_name='KML Image (.jpg, .png, .tiff or whatever)')),
                ('otherfile', models.FileField(blank=True, upload_to='', verbose_name='Other files of note can be uploaded here.')),
                ('notes', models.TextField(default='', verbose_name='Describe your intended flight route or the operations you will perform. Please provide an address as well.')),
            ],
        ),
    ]
