# Generated by Django 4.0.4 on 2022-05-10 04:32

from django.db import migrations, models
import flightplan.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.CharField(max_length=150, verbose_name='Pilot in Command')),
                ('vo', models.CharField(max_length=150, verbose_name='Visual Observer')),
                ('tp', models.TextField(blank=True, verbose_name='Test Personnel')),
                ('max_speed', models.FloatField(verbose_name='Max Speed (in m/s)')),
                ('max_altitude', models.FloatField(verbose_name='Max Altitude (in m)')),
                ('testcardfile', models.FileField(upload_to='', validators=[flightplan.models.validate_ppt_file_extension], verbose_name='Flight Test Card')),
                ('hazardpatternfile', models.FileField(upload_to='', validators=[flightplan.models.validate_ppt_file_extension], verbose_name='Hazard Pattern Card')),
                ('kmlfile', models.FileField(upload_to='', validators=[flightplan.models.validate_ppt_file_extension], verbose_name='KML File')),
            ],
        ),
    ]
